# Generated by Django 4.2.29 on 2026-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('PHONE', 'Phone'), ('BADGE', 'Badge'), ('HEADSET', 'Headset'), ('KEYBOARD', 'Keyboard'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depreciation_months', models.PositiveIntegerField(default=36)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('ASSIGNED', 'Assigned'), ('IN_REPAIR', 'In repair'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], default='IN_STOCK', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
    ]
