# Generated by Django 4.2.29 on 2026-03-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_physical_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='physical_location',
            field=models.CharField(blank=True, choices=[('IT_ROOM', 'IT room'), ('SERVER_ROOM', 'Server room'), ('RECEPTION', 'Reception'), ('WITH_OWNER', 'With owner'), ('OTHER', 'Other')], default='IT_ROOM', max_length=20),
        ),
    ]
