# Generated by Django 4.2.29 on 2026-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='returned_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
