# Generated by Django 4.2.29 on 2026-03-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ASSIGNED')), fields=('asset',), name='unique_active_assignment_per_asset'),
        ),
    ]
