# Generated by Django 4.2.29 on 2026-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('ENGINEERING', 'Engineering'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('OFFBOARDING', 'Offboarding'), ('INACTIVE', 'Inactive')], default='ONBOARDING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
